
public class listManager {
	static tutor[] tutorList = {
			new tutor("May Yan","maykyyca@gmail.com","Semi 11"),
			new tutor("Kanika Soni ","kanika.soni@gmail.com","Semiahmoo Secondary , grade 11 "),
			new tutor("Patrick Zhang","Patrickyizhang@gmail.com","Semiahmoo Gr.11"),
			new tutor("Jacky Wang","furiouluvsmc@gmail.com","Semi 10"),
			new tutor("Annu Anand","anshitaanand07@gmail.com","Semi 12"),
			new tutor("Tony Zong","tonyjjzong@gmail.com","semi 11 IB pathway 2"),
			new tutor("Paulina Gustov","paulinagustov@gmail.com","Semi 11"),
			new tutor("Ghazlia Mehdi","ghazliamehdi2004@gmail.com","Semi 11 full IB path way 2"),
			new tutor("Michael Lin","michaellin0902@gmail.com","semi 11 "),
			new tutor("Ethan Wang","e02.c716@gmail.com","Semi Grade 12"),
			new tutor("Navi Kaur","navikaur2005@gmail.com","Panorama Ridge Secondary grade 10"),
			new tutor("Nishesh Kumar Jain","nishesh.kumarjain@gmail.com","semi grade 9"),
			new tutor("Ken Qi ","kenqi2004j@gmail.com","Semi Gr11"),
			new tutor("Heidi Wang","Heidiyf29@gmail.com","Semi Gr.11"),
			new tutor("Daniel Lu","daniellu4236@gmail.com","Semi Gr.12"),
			new tutor("Celena Chen","1215747568@qq.com","Semi Gr.11"),
			new tutor("Frank Li","lbh040505@gmail.com","Semi Gr11"),
			new tutor("Tyler Gosal","tylergosal@gmail.com","Semi Gr.11"),
			new tutor("Michael Zhou","michael49zhou@gmail.com","Semi grade 9"),
			new tutor("Defne sametoglu","Defnesametoglu@gmail.com ","Semiahmoo Secondary IB pathway one"),
			new tutor("Michael Zheng","michaelzkf@gmail.com","Semi 10"),
			new tutor("Jingyi Zhang","Jingyizhang2004@gmail.com","Semi11"),
			new tutor("Celina Chen","Celinachen0609@qq.com","Semi Grade 11 IB path way 2"),
			new tutor("Anny Gao","gq913046668@gmail.com","Grade 11, Semi partial math"),
			new tutor("Avani Mahil","avanikmahil@gmail.com ","Semi Grade 10"),
			new tutor("Gurik Mangat","gurikmangat8@gmail.com","Semi 11 IB path 1"),
			new tutor("Rachel Li","lirachel0522@gmail.com","semi grade 11 path 2"),
			new tutor("Olivia Partridge","emailoliviamae@gmail.com","Elgin grade 11"),
			new tutor("Guneev Dhillon","gunedhil@gmail.com","Semi grade 9"),
			new tutor("Jasmine Atwal","Jrkomal100@gmail.com","Kwantlen Park Secondary, Grade 12"),
			new tutor("Jeffrey Ku","xiaodouku@gmail.com","SAIL Academy, Grade 10"),
			new tutor("Amrita Johal","amritaj004@gmail.com","Kwantlen Park Secondary, grade 11"),
			new tutor("Ethan Fan","ethanycfan@gmail.com","Semi grade 12 "),
			new tutor("Omar Ahmed","omarahmedabdulfattah24@gmail.com","Gr 10 Surrey Academy Of Innovative Learning "),
			new tutor("Takara","takara.s.allen@gmail.com","Semiahmoo grade 10"),
			new tutor("Harvey","harveyzheng@yahoo.com","Semi grade 11"),
			new tutor("Helen Huang","helenhuang15.ca@gmail.com","semi grade 10"),
			new tutor("Avani Bhangu","monbhangu@gmail.com","SAIL Acadamy grade 10"),
			new tutor("Effie Chen ","effiechen1017@gmail.com","Semi grade 9"),
			new tutor("Sharon  Yang","sysharonyang@gmail.com","semi grade 10"),
			new tutor("Catherine Luan","24224@mychs.ca","Crofton House School. Grade 9"),
			new tutor("Vivi Huang","vivihuang.ca@gmail.com","semi grade 10"),
			new tutor("Aqsa Agro","agro.aqsa21@gmail.com","Surrey Academy of Innovative Learning gr.10"),
			new tutor("Alvina Chen","sarina_feng@hotmail.com","Semi grade 9"),
			new tutor("Adele Cheung ","0317adele@gmail.com","Semiahmoo grade 10"),
			new tutor("Anant Aneja","anantjotaneja@gmail.com","semi grade 10"),
			new tutor("Joseph Mai ","jmai7335@gmail.com","Semiahmoo Secondary  grade 11"),
			new tutor("Liz kim","Lizkim0920@gmail.com","semi grade 10"),
			new tutor("Stanford Chang","stanford@hey.com","Semi Grade 11 path2"),
			new tutor("Stanford Chang","stanford@hey.com","Semi Grade 11 path2"),
			new tutor("Emily Chen","emilyy.cyn@gmail.com","Semi - IB 11"),
			new tutor("Lily Zhang","24215@mychs.ca","Crofton House School, Grade 9 "),
			new tutor("Matthew Tsuda","kmmtsuda@gmail.com","Semi grade 11 IB path 2"),
			new tutor("Patrick Gong","patrick04mxg@gmail.com","Semi grade 11"),
			new tutor("Ryan Shen","yunzhen736@gmail.com","semi grade 11 IB path 2"),
			new tutor("Lancy Ding","lancyd920@gmail.com","semi grade path 2"),
			new tutor("Bella Yuan","bellayuan1028@gmail.com","semi grade 11 pathway1"),
			new tutor("Zahila Rehman","zahilarehman@gmail.com","Kwantlen Park Secondary, grade 11"),
			new tutor("Daniel Zhan","danielzhan45578@gmail.com","Semiahmoo Secondary School, Grade 10"),
			new tutor("Zhanran Shi","Shizhanran@126.com","Semiahmoo Secondary, Grade 11 path 1"),
			new tutor("Chloe Turner","Chloeturner899@gmail.com","elgin grade 10"),
			new tutor("Joey Zhou","Joeyzzz61@gmail.com","Semi grade 11 partial IB"),
			new tutor("Nina Yu","Nina200402@gmail.com","Semiahmoo grade 11 IB path way3"),
			new tutor("Joey Zhou","Joeyzzz61@gmail.com","Semi grade 11 partial IB"),
			new tutor("Robin Chen","cazrobin324@gmail.com","Semi grade11 IB path1"),
			new tutor("Jayden(Namhun)Lee ","namhun0226@gmail.com","Semi grade 10 going to take path 3"),
			new tutor("Briya Roopra ","Briyaroopra@gmail.com","Semi grade 11"),
			new tutor("Caroline.xiao","Caroline.xiao.div03@gmail.com","Semiahmoo secondary, grade 9"),
			new tutor("Jayen Biring","jayen.biring@gmail.com","Sullivan Heights Secondary - Grade 11"),
			new tutor("Minsoo Oh","5minsoo.0222@gmail.com","Semiahmoo grade 11 pathway 1"),
			new tutor("Tan Su","tan.su@surreyschools.ca","Semiahmoo IB gr 11 path 1 French"),
			new tutor("Cynthia Shan","Cynthiashan228@gmail.com","Semi grade 11"),
			new tutor("victor yu","victoryu20040331@gmail.com","Elgin park  G11"),
			new tutor("Mackenzie Jean ","mackenziejjean@outlook.com","Elgin Park Secondary, Grade 10"),
			new tutor("Lauren Scoten","laurenscoten@gmail.com","elgin grade 11"),
			new tutor("Sophie Li","sophie.li.div03@gmail.com","Semiahmoo Secondary Grade 9"),
			new tutor("Yuhan Qiu","qiuyuhan66@gmail.com","Elgin Park Secondary Gr.11"),
			new tutor("Daniel Liu","danielliu.3131hi@gmail.com","Elgin grade 8"),
			new tutor("Lena Khadra ","lenakhadra17@gmail.com","Elgin 11"),
			new tutor("Yagmur Omurluoglu ","yagmuromurluoglu@gmail.com","Elgin Park Secondary School Grade 10"),
			new tutor("Beerat Padda","beeratpadda5@gmail.com","Kwantlen park grade10"),
			new tutor("William Huang","williamhuang118@gmail.com","Elgin Park Secondary Grade 10"),
			new tutor("Gracie Wall","graciewall174@gmail.com","Elgin park grade 11"),
			new tutor("Miranda Newell","mnewell2004@gmail.com","Earl Marriott grade 11"),
			new tutor("Anhad Dhingra","anhaddhingra@hotmail.com","Semiahmoo Grade 11"),
			new tutor("Andrea Wu","andreawu588@gmail.com","Crofton House School Grade 9"),
			new tutor("KeShVi Vithlani","keshvi385@gmail.com","Panorama Ridge Secondary, Grade 10"),
			new tutor("Kelly Lim","kelly14000605@gmail.com","Semiahmoo Secondary, Grade 11"),
			new tutor("Bhavjit ","parmdil@gmail.com","Semiahmoo Secondary  and grade 11"),
			new tutor("Simran Baryar","simrankbaryar@gmail.com","Semiahmoo Secondary, grade 11partial IB"),
			new tutor("Brandon Zhang","afoo31@icloud.com","Full IB grade 11"),
			new tutor("Hannah Wang","hannahcola8@gmail.com","Moscrop Secondary grade 11"),
			new tutor("Lucy Yu","Jiayi5639@gmail.com","Crofton House School grade 10"),
			new tutor("Awa Wen","awasehun0412@gmail.com","semi grade 11"),
			new tutor("Aleena Tojo","aleenatojo1@gmail.com","Panorama Ridge Secondary grade 11"),
			new tutor("Gurseerat Sumal","sumalgurseerat@gmail.com","Ecolè Panorama Ridge Secondary School"),
			new tutor("Shania Tan","shaniatan0116@gmail.com","Elgin Park Secondary; Grade 10"),
			new tutor("Yingying Ren (Ontario, time +4h) ","pren1@ocdsb.ca","Earl of March Secondary, new Grade 11"),
			new tutor("Hardil Klair","Hardilklair7@gmail.com","Ecole Panorama Ridge . Grade 12"),
			new tutor("Rishika Koshal","rishikas3333@gmail.com ","Panorama Ridge Secondary Grade 9"),
			new tutor("Faiza Arodia ","Faizarodia@gmail.com","Panorama Ridge Secondary School, grade 11"),
			new tutor("Kristen Hashimoto","kristen.hashimoto@gmail.com","Semiahmoo Secondary, grade 11"),
			new tutor("Simran Dhesi","simran_dhesi@icloud.com","Panorama Ridge Secondary - Grade 12"),
			new tutor("Angela Xu","axuotaku@gmail.com","Semiahmoo Secondary gr.12"),
			new tutor("Dalreen Kaur","dalreenkaur@gmail.com","Panorama Ridge Secondary, Grade 12"),
			new tutor("Anureet Grewal","anureetgrewal2019@gmail.com","Panorama Ridge secondary.   (10)"),
			new tutor("Eesha Rehman","eesha079@gmail.com","Sullivan Heights Secondary, grade 12"),
			new tutor("Mia Luo","marshonastick@gmail.com","sangdun.joyce.2017@icloud.com"),
			new tutor("Kevin Wang","kevin526nj@gmail.com","Semiahmoo Secondary Grade 10"),
			new tutor("Clement Zhou","cz52013141834@gmail.com","Elgin Park, grade 9")
	};
	static tutee[] tuteeList = {
			new tutee("harpreet","hnagra82@gmail.com"),
			new tutee("jasleen ","hnagra82@gmail.com"),
			new tutee("Briya Roopra ","Briyaroopra@gmail.com"),
			new tutee("Wyatt and Chelsea Parker","parkerlp@hotmail.com"),
			new tutee("Briya ","Briyaroopra@gmail.com"),
			new tutee("Carol","lizhizho@gmail.com"),
			new tutee("Jaxson Navarro","aman.navarro@shaw.ca"),
			new tutee("Rhea","charlieyy@yahoo.com"),
			new tutee("Aahna","charlieyy@yahoo.com"),
			new tutee("Summer Bains","avtarbains_7@hotmail.com"),
			new tutee("Senka","bojana.radinkovic@gmail.com"),
			new tutee("Brandie (students name - Liam)","Brandielynngrant@gmail.com"),
			new tutee("Nasra Maamiry","nasraet@gmail.com"),
			new tutee("Deb Ziolkoski","Deborah.ziolkoski@gmail.com"),
			new tutee("Aarav kohli","Sonia_k@live.ca"),
			new tutee("Khuvira Sugunan ","madhumitha_accet04@yahoo.com"),
			new tutee("Epik Bothe","sharmichelle2002@yahoo.com"),
			new tutee("Bella McIntosh","gmcintosh@gmail.com"),
			new tutee("Ravneet","Ravneet_dhaliwal@hotmail.com"),
			new tutee("XIANGYU WANG","anita130923@gmail.com"),
			new tutee("Draven","Katkrumbum@gmail.com"),
			new tutee("Daivyan Obiajunwa","matdivdavy@yahoo.com"),
			new tutee("Saira Ludu","gurpreetkaurmanu@gmail.com"),
			new tutee("Cyenna kahlon","Kahlonravin@gmail.com"),
			new tutee("Bhavgeet Sandhu","Sandhu_mk@hotmail.com"),
			new tutee("Senka Radinkovic","bojana.radinkovic@gmail.com"),
			new tutee("Bhavgeet Sandhu","Sandhu_mk@hotmail.com"),
			new tutee("Bhavgeet Sandhu","Sandhu_mk@hotmail.com"),
			new tutee("Mia Ramos-Sanchez","winnieyu628@hotmail.com"),
			new tutee("sarah B","cswanson92@hotmail.ca"),
			new tutee("Rachel ","rachelblades66@gmail.com"),
			new tutee("Emily Hyun","mjyoun@gmail.com"),
			new tutee("Emily Hyun","mjyoun@gmail.com"),
			new tutee("Peyton Zhu","tanyazhu518@yahoo.com"),
			new tutee("Joy Waithira Njoroge","wambuinjorogejoy@gmail.com"),
			new tutee("Yein Kim","arasynn@naver.com"),
			new tutee("Harshveer ","Ramangrewal1221@gmail.com"),
			new tutee("Amber","Ramangrewal1221@gmail.com"),
			new tutee("Bhavgeet ","Sandhu_ml@hotmail.com"),
			new tutee("Bhavgeet ","Sandhu_ml@hotmail.com"),
			new tutee("Gavin Booth","gavinbooth@outlook.com"),
			new tutee("Classik Bothe","sharmichelle2002@yahoo.com"),
			new tutee("Ralph Rarama","crizeldacalate@yahoo.ca"),
			new tutee("Angela Eve Rarama","crizeldacalate@yahoo.ca"),
			new tutee("Tim Guo","Wenlin9993@gmail.com"),
			new tutee("Bowen ","candibowenryan@gmail.com"),
			new tutee("Kallen Sakamaki","yuko_sakamaki@hotmail.com"),
			new tutee("Pavneet Lasher","lashergary@hotmail.com"),
			new tutee("Arjun Lasher","lashergary@hotmail.com"),
			new tutee("Jacob huynh","Monica18vn@yahoo.com"),
			new tutee("Jacob ","Angelasilva0620@gmail.com"),
			new tutee("Jacob ","Angelasilva0620@gmail.com"),
			new tutee("Davyonne Obiajunwa","matdivdavy@yahoo.com"),
			new tutee("Anmol Singh gill","Rajsarbjit81@gmail.com"),
			new tutee("Anmol Singh gill","Rajvindergill133@gmail.com"),
			new tutee("Sabhneet","llakh57@yahoo.com"),
			new tutee("Abinaya","psanthann@hotmail.com"),
			new tutee("Lisa Marfori","ricebean1001@gmail.com"),
			new tutee("Omkar kalis","rajnibdev5@gmail.com "),
			new tutee("preet","hnagra82@gmail.com"),
			new tutee("Ralph Israel Rarama","crizeldacalate@yahoo.ca"),
			new tutee("RALPH  ISRAEL RARAMA","crizeldacalate@yahoo.ca"),
			new tutee("RALPH ISRAEL RARAMA","crizeldacalate@yahoo.ca"),
			new tutee("Stewart","lingjieai@gmail.com"),
			new tutee("NAVNEET UPPAL","aman_deep78686@yahoo.com"),
			new tutee("Karanvir uppal","aman_deep78686@yahoo.com"),
			new tutee("Yejun Kim","bryan.kims.mr@gmail.com"),
			new tutee("Kai","handong0413@gmail.com"),
			new tutee("Alvina","Charlieyy@yahoo.com"),
			new tutee("Aahna","Charlieyy@yahoo.com"),
			new tutee("Miley","mileymurillo@gmail.com"),
			new tutee("Anmol Singh ","Rajvindergill133@gmail.com"),
			new tutee("Anmol Singh ","Rajvindergill133@gmail.com"),
			new tutee("Omkar Kalia","rajnibdev5@gmail.com"),
			new tutee("Armaan","kanikaseth97@gmail.com"),
			new tutee("Matthew Iwabu","Doris_kim@hotmail.com"),
			new tutee("Oliver iwabu","Doris_kim@hotmail.com"),
			new tutee("Harkaranvir Singh","Jitkuljit@hotmail.it"),
			new tutee("Ryan Lu","echo83805@gmail.com"),
			new tutee("Riley Munro ","Munroaurora@live.ca "),
			new tutee("Alvina","charlieyy@yahoo.com"),
			new tutee("Arjun Ghuman","sarbjit_ghuman2003@yahoo.com"),
			new tutee("Naya","tasnimshahubi@hotmail.com"),
			new tutee("Derek Liu","dukecc27@gmail.com"),
			new tutee("Duke Liu","dukecc27@gmail.com"),
			new tutee("Tim Guo(Fri)","wenlin9993@gmail.com"),
			new tutee("Tim Guo(Thur)","wenlin9993@gmail.com"),
			new tutee("Manvi jassal","Sonigurav-143@hotmail.ca "),
			new tutee("Sabhneet singh","Llakh57@yahoo.com"),
			new tutee("Andy Li","leelily40@hotmail.com"),
			new tutee("Manvi jassal","Sonigurav-143@hotmail.ca "),
			new tutee("Daivyan Obiajunwa","matdivdavy@yahoo.com"),
			new tutee("Chloe Luo","ylorange@gmail.com"),
			new tutee("Grady","eparr@shaw.ca"),
			new tutee("Aarav kohli ","Sonia_k@live.ca"),
			new tutee("Aarav kohli ","Sonia_k@live.ca"),
			new tutee("Damon Atwal","ninasidhu1@hotmail.com"),
			new tutee("Jaxson Romanyk","jeffromanyk@me.com"),
			new tutee("Colton Kingdon","jeffkingdon@yahoo.ca"),
			new tutee("Colton Kingdon","jeffkingdon@yahoo.ca"),
			new tutee("Heath ","rachelblades66@gmail.com"),
			new tutee("Mohammed (Mo)","Mohammed82004@gmail.com"),
			new tutee("Mohammed (Mo)","Mohammed82004@gmail.com"),
			new tutee("Mohammed (Mo)","Mohammed82004@gmail.com"),
			new tutee("Sophia ","Lisasaran76@gmail.com"),
			new tutee("Parin Sachdeva ","shallyurs@gmail.com"),
			new tutee("Briya Roopra ","Briyaroopra@gmail.com"),
			new tutee("merlin","Sleo12324@gmail.com"),
			new tutee("merlin","Sleo12324@gmail.com"),
			new tutee("Eason wu","jennywu2305@gmail.com"),
			new tutee("Ryan Lu","echo83805@gmail.com"),
			new tutee("Ryan Lu","echo83805@gmail.com"),
			new tutee("Victoria","vickiyuan@gmail.com"),
			new tutee("Hudson Burns","juliekpburns@gmail.com"),
			new tutee("Amelia Ani","itsmithu@gmail.com"),
			new tutee("Hadir El Sakhawy ","hadirsakhawy@gmail.com"),
			new tutee("Emma "," Muqingzhang0@gmail.com"),
			new tutee("Victoria Cai","vickiyuan@gmail.com"),
			new tutee("merlin","Sleo12324@gmail.com"),
			new tutee("Logan Klassen","Lwck2011@gmail.com"),
			new tutee("Logan Klassen","Lwck2011@gmail.com"),
			new tutee("Grace Wang","carriewd@yahoo.com"),
			new tutee("Joshua Ta","joshuata813@gmail.com"),
			new tutee("Jeffery Cheng","sheila05ca@yahoo.ca"),
			new tutee("Jeffery Cheng","sheila05ca@yahoo.ca"),
			new tutee("Celeste","celestechu9@gmail.com"),
			new tutee("Saira ","Gurpreetkaurmanu@gmail.com"),
			new tutee("Maya Lowe","alison_lowe@shaw.ca"),
			new tutee("Justin  Chen","Jessie19990808@gmail.com"),
			new tutee("Justin Chen","jessie19990808@gmail.com"),
			new tutee("Ava Litchfield","Litchfield@shaw.ca"),
			new tutee("lieu cao","caoyuanyuan2002@163.com"),
			new tutee("Ava Litchfield","Litchfield@shaw.ca"),
			new tutee("Jacky Wang","Furiouluvsmc@gmail.com"),
			new tutee("Ashleen kaur Gill ","rajvindergill133@gmail.com"),
			new tutee("Andrew Chen","shiannie@gmail.com"),
			new tutee("Ivan Hou ","ZCL611@yahoo.com"),
			new tutee("Eric","wangran20724@gmail.com"),
			new tutee("Sindy Fan","shirleyzhou061@gmail.com"),
			new tutee("Canssy Fan","shirleyzhou061@gmail.com"),
			new tutee("Ariel Xiao","panda7823@163.com"),
			new tutee("Molly zhang","597387681@qq.com"),
			new tutee("Kamie","imhere721271@qq.com"),
			new tutee("Tanya Gao","graciehgao@gmail.com"),
			new tutee("Kaden","imhere721271@qq.com"),
			new tutee("Harrison","helenma782@hotmail.com"),
			new tutee("Marisha","Korenheron@gmail.com"),
			new tutee("Kamie","imhere721271@qq.com"),
			new tutee("Alexa Romanyk ","jeffromanyk@me.com"),
			new tutee("Joshua Ren","Jrenmagi@gmail.com"),
			new tutee("Taoyi Zhang","taoyi2018@hotmail.com"),
			new tutee("Leo Choi","Jazzjm25@gmail.com"),
			new tutee("Hadir ","hadirsakhawy@gmail.com"),
			new tutee("Bowen Zhan ","bowen6978@gmail.com"),
			new tutee("Jayden ","jaypang360@gmail.com"),
			new tutee("Duke Liu","dukecc27@gmail.com"),
			new tutee("Kaden","imhere721271@qq.com"),
			new tutee("Melody Mo","momelody33@gmail.com"),
			new tutee("Stanley Jin","hija16627@gmail.com"),
			new tutee("Manraj ","Dildeep.lasher91@yahoo.com"),
			new tutee("Brandon Zhang","afoo31@icloud.com"),
			new tutee("Jax Romanyk ","jeffromanyk@me.com"),
			new tutee("Alyssa","Ckataria@icloud.com"),
			new tutee("Chloe Rose","Markandsarahrose@gmail.com"),
			new tutee("Senka Radinkovic","bojana.radinkovic@gmail.com"),
			new tutee("JASPER ZHAI","JOHNNY.ZHAI@gmail.com"),
			new tutee("Enoch Bao","xiangsula@gmail.com"),
			new tutee("Lucy Bao","xiangsula@gmail.com"),
			new tutee("Emma Ding","vickyding119@gmail.com"),
			new tutee("ANDY2","yebobo@hotmial com"),
			new tutee("Emmy","mnlily6696@gmail.com"),
			new tutee("Anson Lyu","kymelaine@hotmail.com"),
			new tutee("Stewart Hayes","xuehayes@gmail.com"),
			new tutee("Andy3","Lydiali712214@gmail.com"),
			new tutee("Camille","kungao0825@gmail.com"),
			new tutee("Ezra ","liubo2055@gmail.com")
	};
	
	public static tutor findTutor(String name){
		for(int i = 0; i<tutorList.length; i++) {
			if(change(tutorList[i].getName()).contains(change(name))) {
				return tutorList[i];
			}
		}
		return null;
	}
	public static tutee findTutee(String name){
		for(int i = 0; i<tuteeList.length; i++) {
			if(change(tuteeList[i].getName()).contains(change(name))) {
				return tuteeList[i];
			}
		}
		return null;
	}
	
	private static String change(String word) {
		return word.replaceAll(" ","").toLowerCase();
	}
}
